# Generated by Django 5.1.1 on 2024-09-14 20:28

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('symbols_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField()),
                ('title', models.TextField()),
                ('text', models.TextField(blank=True, null=True)),
                ('url', models.URLField(max_length=500)),
                ('site', models.CharField(blank=True, max_length=255, null=True)),
                ('sentiment_classification', models.CharField(max_length=50)),
                ('sentiment_score', models.DecimalField(decimal_places=8, max_digits=14)),
                ('weighted_sentiment', models.DecimalField(blank=True, decimal_places=8, max_digits=14, null=True)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_data', to='symbols_app.tickers')),
            ],
            options={
                'db_table': 'Hybrid_Trading_Schema"."news_data',
                'indexes': [models.Index(fields=['ticker', 'published_date'], name='news_data_ticker__02d44f_idx'), models.Index(fields=['sentiment_score'], name='news_data_sentime_ee600a_idx'), django.contrib.postgres.indexes.GinIndex(fields=['keywords'], name='idx_news_data_keywords')],
                'unique_together': {('ticker', 'published_date', 'url')},
            },
        ),
    ]
