# Generated by Django 5.1.1 on 2024-09-14 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickers',
            fields=[
                ('ticker_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sector', models.CharField(blank=True, max_length=50, null=True)),
                ('industry', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tickers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TickerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(max_length=50)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.DO_NOTHING, to='symbols_app.tickers', to_field='ticker')),
            ],
            options={
                'db_table': 'ticker_data',
                'managed': True,
                'unique_together': {('ticker', 'data_type')},
            },
        ),
    ]
