# Generated by Django 5.1.1 on 2024-09-14 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('symbols_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_portfolio_value', models.FloatField(blank=True, null=True)),
                ('trade_log', models.JSONField(blank=True, null=True)),
                ('backtest_date', models.DateTimeField(blank=True, null=True)),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.DO_NOTHING, to='symbols_app.tickers', to_field='ticker')),
            ],
            options={
                'db_table': 'Hybrid_Trading_Schema.backtest_results',
                'unique_together': {('ticker', 'backtest_date')},
            },
        ),
        migrations.CreateModel(
            name='BacktestResultsTradeLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('date', models.DateTimeField()),
                ('portfolio_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, to='symbols_app.tickers', to_field='ticker')),
            ],
            options={
                'db_table': 'Hybrid_Trading_Schema.backtest_results_trade_logs',
                'indexes': [models.Index(fields=['ticker', 'date', 'action'], name='idx_bt_logs_tda')],
                'unique_together': {('ticker', 'date', 'action')},
            },
        ),
    ]
