# Generated by Django 5.1.1 on 2024-09-14 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('symbols_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineBacktestLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_message', models.TextField()),
                ('log_level', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pipeline_backtest_logs', to='symbols_app.tickers', to_field='ticker')),
            ],
            options={
                'db_table': 'pipeline_backtest_logs',
                'managed': True,
                'unique_together': {('ticker', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='PipelineBacktestProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('estimated_time_remaining', models.FloatField(blank=True, null=True)),
                ('completed_tasks', models.IntegerField(default=0)),
                ('total_tasks', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pipeline_backtest_progress', to='symbols_app.tickers', to_field='ticker')),
            ],
            options={
                'db_table': 'pipeline_backtest_progress',
                'managed': True,
                'unique_together': {('ticker', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='PipelineBacktestResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historical_data', models.JSONField()),
                ('prophet_forecast', models.JSONField()),
                ('real_time_data', models.JSONField(blank=True, null=True)),
                ('technical_indicators', models.JSONField(blank=True, null=True)),
                ('backtest_result', models.JSONField()),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pipeline_backtest_results', to='symbols_app.tickers', to_field='ticker')),
            ],
            options={
                'db_table': 'pipeline_backtest_results',
                'managed': True,
                'unique_together': {('ticker', 'created_at')},
            },
        ),
        migrations.CreateModel(
            name='PipelineGeneratedSignals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dynamic_signals', models.JSONField(blank=True, null=True)),
                ('prediction_signals', models.JSONField(blank=True, null=True)),
                ('mean_reversion_momentum_signals', models.JSONField(blank=True, null=True)),
                ('volatility_reversion_signals', models.JSONField(blank=True, null=True)),
                ('trading_signals', models.JSONField(blank=True, null=True)),
                ('value_seeker_signals', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pipeline_generated_signals', to='symbols_app.tickers', to_field='ticker')),
            ],
            options={
                'db_table': 'pipeline_generated_signals',
                'managed': True,
                'unique_together': {('ticker', 'created_at')},
            },
        ),
        migrations.CreateModel(
            name='PipelinePerformanceInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_results', models.JSONField(blank=True, null=True)),
                ('dynamic_decision', models.CharField(blank=True, default='Hold', max_length=10, null=True)),
                ('prediction_decision', models.CharField(blank=True, default='Hold', max_length=10, null=True)),
                ('sentiment_score', models.FloatField(blank=True, default=0.0, null=True)),
                ('weighted_sentiment', models.FloatField(blank=True, default=0.0, null=True)),
                ('analyst_score', models.FloatField(blank=True, default=0.0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pipeline_performance_input', to='symbols_app.tickers', to_field='ticker')),
            ],
            options={
                'db_table': 'pipeline_performance_input',
                'managed': True,
                'unique_together': {('ticker', 'created_at')},
            },
        ),
        migrations.CreateModel(
            name='PipelinePerformanceLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_message', models.TextField()),
                ('log_level', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pipeline_performance_logs', to='symbols_app.tickers', to_field='ticker')),
            ],
            options={
                'db_table': 'pipeline_performance_logs',
                'managed': True,
                'unique_together': {('ticker', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='PipelinePerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharpe_ratio', models.FloatField(blank=True, null=True)),
                ('sortino_ratio', models.FloatField(blank=True, null=True)),
                ('max_drawdown', models.FloatField(blank=True, null=True)),
                ('volatility', models.FloatField(blank=True, null=True)),
                ('annualized_return', models.FloatField(blank=True, null=True)),
                ('alpha', models.FloatField(blank=True, null=True)),
                ('beta', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pipeline_performance_metrics', to='symbols_app.tickers', to_field='ticker')),
            ],
            options={
                'db_table': 'pipeline_performance_metrics',
                'managed': True,
                'unique_together': {('ticker', 'created_at')},
            },
        ),
        migrations.CreateModel(
            name='PipelineSignalGenerationLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_message', models.TextField()),
                ('log_level', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pipeline_signal_generation_logs', to='symbols_app.tickers', to_field='ticker')),
            ],
            options={
                'db_table': 'pipeline_signal_generation_logs',
                'managed': True,
                'unique_together': {('ticker', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='PipelineTickerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historical_data', models.JSONField(blank=True, null=True)),
                ('real_time_data', models.JSONField(blank=True, null=True)),
                ('technical_indicators', models.JSONField(blank=True, null=True)),
                ('prophet_forecast', models.JSONField(blank=True, null=True)),
                ('financial_ratios', models.JSONField(blank=True, null=True)),
                ('financial_scores', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pipeline_ticker_data', to='symbols_app.tickers', to_field='ticker')),
            ],
            options={
                'db_table': 'pipeline_ticker_data',
                'managed': True,
                'unique_together': {('ticker', 'created_at')},
            },
        ),
        migrations.CreateModel(
            name='PipelineTradeExecutionLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_message', models.TextField()),
                ('log_level', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pipeline_trade_execution_logs', to='symbols_app.tickers', to_field='ticker')),
            ],
            options={
                'db_table': 'pipeline_trade_execution_logs',
                'managed': True,
                'unique_together': {('ticker', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='PipelineTradeResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_result', models.JSONField()),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pipeline_trade_results', to='symbols_app.tickers', to_field='ticker')),
            ],
            options={
                'db_table': 'pipeline_trade_results',
                'managed': True,
                'unique_together': {('ticker', 'created_at')},
            },
        ),
        migrations.CreateModel(
            name='PipelineTradeSignals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dynamic_signals', models.JSONField(blank=True, null=True)),
                ('prediction_signals', models.JSONField(blank=True, null=True)),
                ('mrms_signals', models.JSONField(blank=True, null=True)),
                ('vrs_signals', models.JSONField(blank=True, null=True)),
                ('trading_signals', models.JSONField(blank=True, null=True)),
                ('value_seeker_signals', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pipeline_trade_signals', to='symbols_app.tickers', to_field='ticker')),
            ],
            options={
                'db_table': 'pipeline_trade_signals',
                'managed': True,
                'unique_together': {('ticker', 'created_at')},
            },
        ),
    ]
