# Generated by Django 5.1.1 on 2024-09-14 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('symbols_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstantBacktestResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('signal', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('action', models.CharField(max_length=10)),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, to='symbols_app.tickers', to_field='ticker')),
            ],
            options={
                'db_table': 'instant_backtest_results',
                'managed': True,
                'unique_together': {('ticker', 'date', 'signal')},
            },
        ),
        migrations.CreateModel(
            name='MeanReversionMomentumSignals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('action', models.CharField(max_length=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('current_price', models.FloatField()),
                ('moving_average', models.FloatField(blank=True, null=True)),
                ('momentum', models.FloatField(blank=True, null=True)),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, to='symbols_app.tickers', to_field='ticker')),
            ],
            options={
                'db_table': 'mean_reversion_momentum_signals',
                'managed': True,
                'unique_together': {('ticker', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PredictionSignals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('action', models.CharField(max_length=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('current_price', models.FloatField()),
                ('predicted_today', models.FloatField(blank=True, null=True)),
                ('predicted_5_days_out', models.FloatField(blank=True, null=True)),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, to='symbols_app.tickers', to_field='ticker')),
            ],
            options={
                'db_table': 'prediction_signals',
                'managed': True,
                'unique_together': {('ticker', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ValueSeekerSignals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('signal', models.CharField(max_length=10)),
                ('quick_ratio', models.FloatField(blank=True, null=True)),
                ('current_ratio', models.FloatField(blank=True, null=True)),
                ('gross_profit_margin', models.FloatField(blank=True, null=True)),
                ('operating_profit_margin', models.FloatField(blank=True, null=True)),
                ('net_profit_margin', models.FloatField(blank=True, null=True)),
                ('debt_equity_ratio', models.FloatField(blank=True, null=True)),
                ('interest_coverage', models.FloatField(blank=True, null=True)),
                ('price_earnings_ratio', models.FloatField(blank=True, null=True)),
                ('price_book_value_ratio', models.FloatField(blank=True, null=True)),
                ('price_sales_ratio', models.FloatField(blank=True, null=True)),
                ('action', models.CharField(max_length=10)),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, to='symbols_app.tickers', to_field='ticker')),
            ],
            options={
                'db_table': 'value_seeker_signals',
                'managed': True,
                'unique_together': {('ticker', 'date')},
            },
        ),
        migrations.CreateModel(
            name='VolatilityReversionSignals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('action', models.CharField(max_length=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('current_price', models.FloatField()),
                ('upper_band', models.FloatField(blank=True, null=True)),
                ('lower_band', models.FloatField(blank=True, null=True)),
                ('rsi', models.FloatField(blank=True, null=True)),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, to='symbols_app.tickers', to_field='ticker')),
            ],
            options={
                'db_table': 'volatility_reversion_signals',
                'managed': True,
                'unique_together': {('ticker', 'date')},
            },
        ),
    ]
